### ISSUE TITLE
Несколько одинаковых товаров с маркировкой в чеке

### ISSUE THREAD

**Issue by dalvinsky** [shtrih-m/fr_drv_ng#275]
Здравствуйте.

Такой вопрос. Пытаюсь понять, какая последовательность действий должна быть, если количество маркированного товара больше одного (одинакового товара, одна и та же номенклатура)

Работаю через драйвер linux_1.6.0.600 через веб-сокет (console_test_fr_drv_ng-1.6)

Даю следующую последовательность команд:

1.
"method":"FNCheckItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383031313231354e6b6a53415653565a42453a1d3931454530391d393247624d4e6c42764935535a486733496a6130384f37734a4b74764976672b44776b7331544a4679375a58733d","ItemStatus":1,"CheckItemMode":0,"TLVDataHex":""}

Ответ:
{"jsonrpc":"2.0","result":{"CheckItemLocalError":1,"CheckItemLocalResult":0,"KMServerCheckingStatus":15,"KMServerErrorCode":0,"MarkingType2":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет","TLVData":"QggEAC3IsGU5CAEAANUHAQAPPQgBAAE0CAEAAw=="},"id":"2"}

2.

"method":"FNAcceptMarkingCode","params":{"Password":30}

Ответ:

{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}

3.

"method":"FNCheckItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383030343231354665544f4d3f5a4f395543221d3931454530391d393232355779774f64666858562b35614b323342394f44452b6d78672f344949666d5330433566436b2f6f76453d
","ItemStatus":1,"CheckItemMode":0,"TLVDataHex":""}

Ответ:

{"jsonrpc":"2.0","result":{"CheckItemLocalError":1,"CheckItemLocalResult":0,"KMServerCheckingStatus":15,"KMServerErrorCode":0,"MarkingType2":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет","TLVData":"QggEAEzIsGU5CAEAANUHAQAPPQgBAAE0CAEAAw=="},"id":"2"}

4.

"method":"FNAcceptMarkingCode","params":{"Password":30}

Ответ:

{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}

5.

"method":"OpenCheck","params":{"Password":30,"CheckType":0}

6.

"method":"FNOperation","params":{"Password":30,"CheckType":1,"Quantity":2.0,"Price":100,"Summ1":200,"Summ1Enabled":1,"TaxValue":0,"TaxValueEnabled":1,"Tax1":0,"Department":0,"PaymentTypeSign":4,"PaymentItemSign":33,"StringForPrinting":"Тестовый товар"}

Ответ:

{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет","Tax1":0},"id":"2"}

7.

"method":"FNSendItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383031313231354e6b6a53415653565a42453a1d3931454530391d393247624d4e6c42764935535a486733496a6130384f37734a4b74764976672b44776b7331544a4679375a58733d"}

Ответ:

{"jsonrpc":"2.0","result":{"MarkingType":17485,"MarkingTypeEx":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}

8.

"method":"FNSendItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383030343231354665544f4d3f5a4f395543221d3931454530391d393232355779774f64666858562b35614b323342394f44452b6d78672f344949666d5330433566436b2f6f76453d"}

Ответ:

{"jsonrpc":"2.0","result":{"Connected":true,"ResultCode":51,"ResultCodeDescription":"Некорректные параметры в команде"},"id":"2"}

Собственно, вопрос. Если количество маркированного товара не 1 штука, а больше, нужно каждый экземпляр отдельной строчкой пробивать? Даже если их будет 50 штук?

**Comment by surfernsk** [comment]
Первое обновить прошивку ФР, второе не забыть о мере количества которую надо передавать.16:31, 24 января 2024 г., dalvinsky ***@***.***>:
Здравствуйте.
Такой вопрос. Пытаюсь понять, какая последовательность действий должна быть, если количество маркированного товара больше одного (одинакового товара, одна и та же номенклатура)
Работаю через драйвер linux_1.6.0.600 через веб-сокет (console_test_fr_drv_ng-1.6)
Даю следующую последовательность команд:



"method":"FNCheckItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383031313231354e6b6a53415653565a42453a1d3931454530391d393247624d4e6c42764935535a486733496a6130384f37734a4b74764976672b44776b7331544a4679375a58733d","ItemStatus":1,"CheckItemMode":0,"TLVDataHex":""}
Ответ:
{"jsonrpc":"2.0","result":{"CheckItemLocalError":1,"CheckItemLocalResult":0,"KMServerCheckingStatus":15,"KMServerErrorCode":0,"MarkingType2":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет","TLVData":"QggEAC3IsGU5CAEAANUHAQAPPQgBAAE0CAEAAw=="},"id":"2"}



"method":"FNAcceptMarkingCode","params":{"Password":30}
Ответ:
{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}



"method":"FNCheckItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383030343231354665544f4d3f5a4f395543221d3931454530391d393232355779774f64666858562b35614b323342394f44452b6d78672f344949666d5330433566436b2f6f76453d
","ItemStatus":1,"CheckItemMode":0,"TLVDataHex":""}
Ответ:
{"jsonrpc":"2.0","result":{"CheckItemLocalError":1,"CheckItemLocalResult":0,"KMServerCheckingStatus":15,"KMServerErrorCode":0,"MarkingType2":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет","TLVData":"QggEAEzIsGU5CAEAANUHAQAPPQgBAAE0CAEAAw=="},"id":"2"}



"method":"FNAcceptMarkingCode","params":{"Password":30}
Ответ:
{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}



"method":"OpenCheck","params":{"Password":30,"CheckType":0}



"method":"FNOperation","params":{"Password":30,"CheckType":1,"Quantity":2.0,"Price":100,"Summ1":200,"Summ1Enabled":1,"TaxValue":0,"TaxValueEnabled":1,"Tax1":0,"Department":0,"PaymentTypeSign":4,"PaymentItemSign":33,"StringForPrinting":"Тестовый товар"}
Ответ:
{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет","Tax1":0},"id":"2"}



"method":"FNSendItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383031313231354e6b6a53415653565a42453a1d3931454530391d393247624d4e6c42764935535a486733496a6130384f37734a4b74764976672b44776b7331544a4679375a58733d"}
Ответ:
{"jsonrpc":"2.0","result":{"MarkingType":17485,"MarkingTypeEx":3,"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"2"}



"method":"FNSendItemBarcode","params":{"Password":30,"BarcodeHex":"303130343632373137393036383030343231354665544f4d3f5a4f395543221d3931454530391d393232355779774f64666858562b35614b323342394f44452b6d78672f344949666d5330433566436b2f6f76453d"}
Ответ:
{"jsonrpc":"2.0","result":{"Connected":true,"ResultCode":51,"ResultCodeDescription":"Некорректные параметры в команде"},"id":"2"}
Собственно, вопрос. Если количество маркированного товара не 1 штука, а больше, нужно каждый экземпляр отдельной строчкой пробивать? Даже если их будет 50 штук?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by surfernsk** [comment]
Если код маркировки разный (уникальный), то тогда одна позиция чека на один код маркировки. Если продаете 20 пар обуви, пусть даже с одним наименованием, то надо в чек передать 20 позиций и к каждой привязать свой код маркировки.Ранее написал про случай с разливным пивом16:31, 24 января 2024 г., dalvinsky ***@***.***>:
Здравствуйте.
Такой вопрос. Пытаюсь понять, какая последовательность действий должна быть, если количество маркированного товара больше одного (одинакового товара, одна и та же номенклатура)
Собственно, вопрос. Если количество маркированного товара не 1 штука, а больше, нужно каждый экземпляр отдельной строчкой пробивать? Даже если их будет 50 штук?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
